services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - frontend-network
    restart: always

networks:
  frontend-network:
    driver: bridge
