services:
  frontend:
    image: nginx:alpine
    container_name: it_tat_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/it-tat.uz-0001/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/it-tat.uz-0001/privkey.pem:/etc/ssl/private/privkey.pem:ro
    restart: always
