
services:
  frontend:
    build:
      context: . # React loyiha papkasi
      dockerfile: Dockerfile
    ports:
      - "8080:80" # HTTP uchun
      - "8444:443" # HTTPS uchun
    volumes:
      - /etc/letsencrypt/live/it-tat.uz/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/it-tat.uz/privkey.pem:/etc/nginx/ssl/privkey.pem
    networks:
      - frontend-network
    restart: always

networks:
  frontend-network:
    driver: bridge