services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: it_tat_frontend:latest
    container_name: it_tat_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/it-tat.uz-0001/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/it-tat.uz-0001/privkey.pem:/etc/ssl/private/privkey.pem:ro
    environment:
      - TZ=Asia/Tashkent
    restart: unless-stopped
