version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: it_tat_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/it-tat.uz-0001:/etc/letsencrypt/live/it-tat.uz-0001:ro
      - /etc/letsencrypt/archive/it-tat.uz-0001:/etc/letsencrypt/archive/it-tat.uz-0001:ro
    restart: unless-stopped
