server {
    listen 443 ssl;
    server_name it-tat.uz www.it-tat.uz;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

# Optional: HTTP -> HTTPS redirect
server {
    listen 80;
    server_name it-tat.uz www.it-tat.uz;
    return 301 https://$host$request_uri;
}
